<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>tpanda.gamepads</groupId>
  <artifactId>tpanda-gamepad-xinput1_3</artifactId>
  <version>0.0.0</version>
  <packaging>jar</packaging>

  <description>tpanda-gamepad-xinput-api の xinput1_3 実装</description>
  <url>https://github.com/2T-T2/tpanda-gamepad-xinput1_3</url>

  <properties>
    <!-- 依存関係バージョン -->
    <junit.version>5.10.2</junit.version>
    <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
    <surefire.version>3.2.5</surefire.version>
    <tpanda.gcc.plugin.version>0.4.0</tpanda.gcc.plugin.version>
    <tpanda.gamepad.xinput.version>0.1.0</tpanda.gamepad.xinput.version>
    <!-- ビルド設定 -->
    <skipTests>true</skipTests>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>19</maven.compiler.source>
    <maven.compiler.target>19</maven.compiler.target>
    <!-- native library ビルド設定 -->
    <jni.lib.classifier><!-- profile によって変化 --></jni.lib.classifier>
    <tpanda.gcc.cxx>g++</tpanda.gcc.cxx>
    <tpanda.gcc.cc>gcc</tpanda.gcc.cc>
  </properties>

  <pluginRepositories>
    <pluginRepository>
      <id>nakigao-maven-repository</id>
      <url>https://2t-t2.github.io/nakigao-maven-repository/</url>
    </pluginRepository>
  </pluginRepositories>

  <repositories>
    <repository>
      <id>nakigao-maven-repository</id>
      <url>https://2t-t2.github.io/nakigao-maven-repository/</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>tpanda.gamepads</groupId>
      <artifactId>tpanda-gamepad-xinput-api</artifactId>
      <version>${tpanda.gamepad.xinput.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <!-- Javaコンパイルの共通設定 -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven.compiler.plugin.version}</version>
          <configuration>
            <compilerArgs>
              <arg>-h</arg>
              <arg>${project.build.directory}/header</arg>
            </compilerArgs>
            <source>${maven.compiler.source}</source>
            <target>${maven.compiler.target}</target>
          </configuration>
        </plugin>
        <!-- ネイティブライブラリビルドの共通設定 -->
        <plugin>
          <groupId>tpanda.maven.plugins</groupId>
          <artifactId>tpanda-gcc-plugin</artifactId>
          <version>${tpanda.gcc.plugin.version}</version>
          <configuration>
            <cc>${tpanda.gcc.cc}</cc>
            <cxx>${tpanda.gcc.cxx}</cxx>
            <sourceDirectory>${project.basedir}/src/main/cpp</sourceDirectory>
            <outputDirectory>${project.build.directory}/objects</outputDirectory>
            <additionalIncludeDirectories>
              <additionalIncludeDirectory>${project.build.directory}/header</additionalIncludeDirectory>
            </additionalIncludeDirectories>
            <includeJNI>true</includeJNI>
            <classifier>${jni.lib.classifier}</classifier>
          </configuration>
        </plugin>
        <!-- UnitTest実行の共通設定 -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${surefire.version}</version>
          <configuration>
            <workingDirectory>${project.build.directory}</workingDirectory>
          </configuration>
        </plugin>
        <!-- mvn site 設定 -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.21.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.9.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>3.6.3</version>
          <configuration>
            <charset>UTF-8</charset>
            <encoding>UTF-8</encoding>
            <docencoding>UTF-8</docencoding>
            <additionalJOptions>
              <additionalJOption>--allow-script-in-comments</additionalJOption>
            </additionalJOptions>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <skipTests>${skipTests}</skipTests>
        </configuration>
      </plugin>
      <plugin>
        <groupId>tpanda.maven.plugins</groupId>
        <artifactId>tpanda-gcc-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>cc-compile</goal>
              <goal>cxx-compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <reportSets>
          <reportSet>
            <reports>
              <report>javadoc</report>
            </reports>
          </reportSet>
        </reportSets>
      </plugin>
    </plugins>
  </reporting>

  <profiles>
    <profile>
      <id>windows-x86_64</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>x86_64</arch>
        </os>
      </activation>
      <properties>
        <skipTests>false</skipTests>
        <tpanda.gcc.cc>x86_64-w64-mingw32-gcc</tpanda.gcc.cc>
        <tpanda.gcc.cxx>x86_64-w64-mingw32-g++</tpanda.gcc.cxx>
        <jni.lib.classifier>jni-win-x86_64</jni.lib.classifier>
      </properties>
    </profile>
    <profile>
      <id>windows-amd64</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>amd64</arch>
        </os>
      </activation>
      <properties>
        <skipTests>false</skipTests>
        <tpanda.gcc.cc>x86_64-w64-mingw32-gcc</tpanda.gcc.cc>
        <tpanda.gcc.cxx>x86_64-w64-mingw32-g++</tpanda.gcc.cxx>
        <jni.lib.classifier>jni-win-x86_64</jni.lib.classifier>
      </properties>
    </profile>
    <profile>
      <id>windows-x86</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>x86</arch>
        </os>
      </activation>
      <properties>
        <skipTests>false</skipTests>
        <tpanda.gcc.cc>i686-w64-mingw32-gcc</tpanda.gcc.cc>
        <tpanda.gcc.cxx>i686-w64-mingw32-g++</tpanda.gcc.cxx>
        <jni.lib.classifier>jni-win-x86</jni.lib.classifier>
      </properties>
    </profile>
    <profile>
      <id>build-for-windows</id>
      <activation>
        <os><family>windows</family></os>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>tpanda.maven.plugins</groupId>
            <artifactId>tpanda-gcc-plugin</artifactId>
            <executions>
              <execution>
                <phase>compile</phase>
                <goals>
                  <goal>link-jni-dll</goal>
                </goals>
                <configuration>
                  <ldflags>-shared -static -Wl,--add-stdcall-alias,-s -lxinput1_3</ldflags>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
